<a href="https://colab.research.google.com/github/suryanshasayth936-ux/Python_Classes/blob/main/Class_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [9]:
df1 = pd.DataFrame({
    'id' : [1, 2, 3, 4],
    'name' : ['Raja', ' Rani', 'Rahul', 'Rhea'],
    'age' : [25,30,35,40]
})

df2 = pd.DataFrame({
    'id' : [3, 4, 5, 6],
    'name' : ['Rahul', ' Rhea', 'Ravi', 'Reena'],
    'age' : [35,40,45,50]
})
df3 = pd.merge(df1, df2, on = 'id', how = 'inner')
df3.rename(columns = {'name_x' : 'Table_1', 'name_y' : 'Table_2'}, inplace = 'True')
df3.rename(columns = {'age_x' : 'Table_1_age', 'age_y' : 'Table_2_age'}, inplace = 'True')

display(df3)

   id Table_1  Table_1_age Table_2  Table_2_age
0   3   Rahul           35   Rahul           35
1   4    Rhea           40    Rhea           40

In [13]:
df4 = pd.merge(df1, df2, on = 'id', how = 'left')
print(df4)
df5 = pd.merge(df1, df2, on = 'id', how = 'right')
print(df5)
df6 = pd.merge(df1, df2, on = 'id', how = 'outer')
print(df6)

   id name_x  age_x name_y  age_y
0   1   Raja     25    NaN    NaN
1   2   Rani     30    NaN    NaN
2   3  Rahul     35  Rahul   35.0
3   4   Rhea     40   Rhea   40.0
   id name_x  age_x name_y  age_y
0   3  Rahul   35.0  Rahul     35
1   4   Rhea   40.0   Rhea     40
2   5    NaN    NaN   Ravi     45
3   6    NaN    NaN  Reena     50
   id name_x  age_x name_y  age_y
0   1   Raja   25.0    NaN    NaN
1   2   Rani   30.0    NaN    NaN
2   3  Rahul   35.0  Rahul   35.0
3   4   Rhea   40.0   Rhea   40.0
4   5    NaN    NaN   Ravi   45.0
5   6    NaN    NaN  Reena   50.0

#Cross Join - Assuming there are x rows in table 1 and y rows in table 2, then total number of rows in resulting table would be x*y, as each row of table one would be compared to each row on the right table.

In [14]:
df7 = pd.merge(df1, df2, how = 'cross')
print(df7)

    id_x name_x  age_x  id_y name_y  age_y
0      1   Raja     25     3  Rahul     35
1      1   Raja     25     4   Rhea     40
2      1   Raja     25     5   Ravi     45
3      1   Raja     25     6  Reena     50
4      2   Rani     30     3  Rahul     35
5      2   Rani     30     4   Rhea     40
6      2   Rani     30     5   Ravi     45
7      2   Rani     30     6  Reena     50
8      3  Rahul     35     3  Rahul     35
9      3  Rahul     35     4   Rhea     40
10     3  Rahul     35     5   Ravi     45
11     3  Rahul     35     6  Reena     50
12     4   Rhea     40     3  Rahul     35
13     4   Rhea     40     4   Rhea     40
14     4   Rhea     40     5   Ravi     45
15     4   Rhea     40     6  Reena     50

#Concat - used to concatenate two tables on either axis = 0 or axis = 1

In [16]:
df8 = pd.concat([df1, df2], axis = 0)
print(df8)

   id   name  age
0   1   Raja   25
1   2   Rani   30
2   3  Rahul   35
3   4   Rhea   40
0   3  Rahul   35
1   4   Rhea   40
2   5   Ravi   45
3   6  Reena   50

In [17]:
df9 = pd.concat([df1, df2], axis = 1)
print(df9)

   id   name  age  id   name  age
0   1   Raja   25   3  Rahul   35
1   2   Rani   30   4   Rhea   40
2   3  Rahul   35   5   Ravi   45
3   4   Rhea   40   6  Reena   50

In [19]:
df8 = pd.concat([df1, df2])
df8 = df8.drop_duplicates(subset = ['id','name'], keep  = 'first')
display(df8)

   id   name  age
0   1   Raja   25
1   2   Rani   30
2   3  Rahul   35
3   4   Rhea   40
2   5   Ravi   45
3   6  Reena   50

In [21]:
df = pd.read_csv('student_data.csv')

In [22]:
df.pivot_table(columns = 'placement_status', index = 'sleep_hours', values = 'exam_score', aggfunc = 'mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [24]:
df.pivot_table(columns = 'study_hours', index = 'sleep_hours', values = 'assignment_completed', aggfunc = 'mean')

#Check for the error

KeyError: 'assignment_completed'

#Hw - 1327, 511, 586, 1050, 175, 181, 182, 262, 184, 185, 1179
#Questions on Pivot Table using ChatGPT