<a href="https://colab.research.google.com/github/suryanshasayth936-ux/Python_Classes/blob/main/Class_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
dct = {
    'name' : ['Tom', 'Nick', 'Krish', 'Jack'],
    'age' : [20, 21, 19, 18],
    'roll' : [1, 2, 3, 4]
}

df = pd.DataFrame(dct, index = ['a','b','c','d'])
display(df)

    name  age  roll
a    Tom   20     1
b   Nick   21     2
c  Krish   19     3
d   Jack   18     4

In [6]:
df = pd.read_csv('student_data.csv')
display(df)
df.head() #displays the first 5 values
df.tail() #displays last 5 values
df.shape #outputs (rows,colums)
df.info() #data about data, like gives information about the information
df.describe()
#25% - > First Quarterly
#50% - > Second Quarterly
#75% - > Third Quarterly

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [ ]:
display(df.columns) #list of columns
display(df.index) #range of indices

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
display(df[['study_hours', 'internet_usage']])
display(df[['study_hours']])
display(df.study_hours)

      study_hours  internet_usage
0               7               7
1               4               3
2              11               6
3               8               8
4               5               6
...           ...             ...
9995            2               7
9996            7               9
9997           10               5
9998           10               5
9999            2              11

[10000 rows x 2 columns]

      study_hours
0               7
1               4
2              11
3               8
4               5
...           ...
9995            2
9996            7
9997           10
9998           10
9999            2

[10000 rows x 1 columns]

0        7
1        4
2       11
3        8
4        5
        ..
9995     2
9996     7
9997    10
9998    10
9999     2
Name: study_hours, Length: 10000, dtype: int64

In [ ]:
display(df.iloc[5:22])

df.loc[df['study_hours']==11, ['study_hours', 'sleep_hours']].iloc[4:8]
#study loc and iloc in depth

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
5,7,40,9,10,0,60,72.33,Placed
6,10,40,4,11,9,50,98.12,Placed
7,3,86,7,3,7,85,100.00,Placed
8,7,72,8,5,18,48,96.81,Placed
9,11,77,4,9,15,69,100.00,Placed
10,11,64,8,8,12,76,100.00,Placed
11,8,65,5,6,4,87,100.00,Placed
12,5,52,6,9,17,89,95.36,Placed
13,4,98,9,2,8,70,100.00,Placed
14,8,67,8,11,3,56,83.49,Placed
15,8,72,7,9,13,87,100.00,Placed
16,3,76,8,10,6,36,63.26,Not Placed
17,6,80,8,10,11,47,91.89,Placed
18,5,69,8,6,6,45,73.69,Placed
19,2,96,8,9,10,46,77.59,Placed
20,8,88,7,4,14,67,100.00,Placed
21,6,87,7,5,6,56,77.19,Placed

     study_hours  sleep_hours
30            11            5
91            11            9
98            11            6
116           11            7

In [ ]:
d2f = df.loc[df['assignments_completed'] == 8].iloc[1]
display(d2f)

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [7]:
df = pd.read_csv('student_data.csv')
df[df['assignments_completed']>3]
df["age"] = 20
# display(df)
df.rename(columns = {'assignments_completed':'assign_completed'}, inplace = True) #rename a column
display(df)
df.drop(columns = ['sleep_hours','internet_usage'])
df["dummy_data"] = " "
display(df)
# df.dropna(['dummy_data'])
#isnull, notnull, fillna, unique,

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status,age,dummy_data
0,7,56,8,7,10,62,100.00,Placed,20,
1,4,69,5,3,8,56,100.00,Placed,20,
2,11,60,7,6,10,45,100.00,Placed,20,
3,8,99,9,8,4,55,90.17,Placed,20,
4,5,52,8,6,8,40,78.82,Placed,20,
...,...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20,
9996,7,98,6,9,4,87,100.00,Placed,20,
9997,10,44,8,5,10,37,95.94,Placed,20,
9998,10,75,7,5,8,52,88.61,Placed,20,
9999,2,70,6,11,16,52,78.96,Placed,20,